### ISSUE TITLE
Missing xml error, just native in wrong ServiceLocator map definition

### ISSUE THREAD

**Issue by grosmar** [DoclerLabs/hexIoC#12]
If i reference a wrong key value, i get a native error:
C:\Progs\Haxe\3.3.0\std/haxe/macro/Context.hx:258: characters 9-46 : Type not found 'IRTMPService'
./api/hexannotation/src/hex/annotation/AnnotationReader.hx:165: characters 32-90 : Called from
./api/hexinject/src/hex/di/annotation/AnnotationReader.hx:32: characters 30-155 : Called from
./api/hexinject/src/hex/di/IInjectorContainer.hx:8: characters 2-11 : Called from
C:\Progs\Haxe\3.3.0\std/haxe/macro/Context.hx:258: characters 9-46 : Called from
./api/hexioc/src/hex/compiler/parser/xml/ClassImportHelper.hx:41: characters 4-27 : Called from
./api/hexioc/src/hex/compiler/parser/xml/XmlCompiler.hx:174: characters 5-55 : Called from
./api/hexioc/src/hex/compiler/parser/xml/XmlCompiler.hx:508: characters 3-83 : Called from
./api/hexioc/src/hex/compiler/parser/xml/XmlCompiler.hx:544: characters 9-79 : Called from
./src/something/Main.hx:45: characters 30-110 : Called from

It looks like this:
`<item map-name="memberChat"> <key type="Class" value="something.service.net.rtmp.IRTMPService"/> <value ref="myRTMPService"/></item>
`
It should point to the xml, not the Context.

**Comment by grosmar** [comment]
Looks like the same with map-type:
`<service id="myRTMPService" type="something.service.net.rtmp.RTMPService" map-type="something.service.net.rtmp.IRTMPService" />`

**Comment by FrancisBourre** [comment]
I think that's not a DSL error. If you check the stacktrace, you can see that it passes through IInjectorContainer and goes finally to AnnotationReader. The annotation reader tries to get IRTMPService property type to build reflection cache for the injector, but it doesn't find it.
I tried to make an hotfix to make the error as fatal and eliminate the stacktrace, but I'm not convinced 100% it's the right option.
