### ISSUE TITLE
Conditions don't avoid elements to be fully processed by XmlCompiler.

### ISSUE THREAD

**Issue by Neverbirth** [DoclerLabs/hexIoC#4]
Having something like:

```xml
<module if="flash" type="FlashModule"/>
```

Will still process the full node even if the condition is false. This is a problem because the type may include code that it's not available under every target.

Using if with includes works as expected, but there are cases where using a single file for different conditions is more clear.

**Comment by FrancisBourre** [comment]
I finally rewrite from scratch the Xml DSL parser. Now everything is handled in the right way and the node/file positions (for throwing errors) are fully reliable. And for sure, the conditional parsing happens everytime at the right time.
