### ISSUE TITLE
DSL errors don't report the right file position

### ISSUE THREAD

**Issue by FrancisBourre** [DoclerLabs/hexIoC#8]
Till PR #3 has been merged, DSL errors don't report the right file position when comments are inserted inside Xml files.

**Comment by FrancisBourre** [comment]
I finally rewrote from scratch the Xml DSL parser. Now everything is handled in the right way, and the node/file positions (for throwing errors) are fully reliable.

**Comment by grosmar** [comment]
Thanks a lot! I'm so happy! :)
